### ISSUE TITLE
Allow a --themes-dir that is not on the default sys.path

### ISSUE THREAD

**Issue by oz-linden** [nojhan/colout#75]
I'd like to have a personal collection of themes, or have one shipped in a package with sources.  At present, specifying a themes directory not on my default python module search path results in an error:
```
  ./colout/colout.py --themes-dir ~/_config/colout --r themes
Traceback (most recent call last):
  File "./colout/colout.py", line 985, in <module>
    load_themes( adir )
  File "./colout/colout.py", line 226, in load_themes
    context["themes"][name] = importlib.import_module(module)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2224, in _find_and_load_unlocked
ImportError: No module named 'colout_llsd'
```

**Comment by nojhan** [comment]
Merged.
