### ISSUE TITLE
Failed to install with pip

### ISSUE THREAD

**Issue by sanmai** [nojhan/colout#88]
Recommended way to install with pip fails.

```
$ sudo pip install colout
Collecting colout
  Using cached colout-0.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-ob3xy1/colout/setup.py", line 25, in <module>
        long_description=open('README.md').read(),
    IOError: [Errno 2] No such file or directory: 'README.md'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ob3xy1/colout/
```

**Comment by knoxknox** [comment]
@sanmai
You can temporarily resolve this by installing the older version.
$ sudo pip install colout==0.3 (https://pypi.python.org/simple/colout/)

**Comment by DiagonalArg** [comment]
Getting the same error.

Note that the tar download at [this location](https://nojhan.github.io/colout/) is version 0.1 (or at least so it says in setup.py).  You may want to update that.

Also, I don't have much experience with python, but shouldn't it be `pip3 install colout`?

**Comment by humbletim** [comment]
here is another way that seems to work for installing the latest version of `colout`:

#### pip3 (python3):
```sh
$ pip3 install --user git+git://github.com/nojhan/colout.git@master

$ colout -r colors
COLORS: black, blue, cyan, green, magenta, none, orange, purple, red, white, yellow
```

#### pip (python2.7):
```sh
$ pip install --user git+git://github.com/nojhan/colout.git@master

# ... then run manually with python2.7 (because 'colout' wrapper is hardcoded to python3):
$ python2.7 -mcolout.colout -r colors
COLORS: black, blue, cyan, green, magenta, none, orange, purple, red, white, yellow

# ... or what I did was patch the installed wrapper script 
$ perl -i -p -e 's{python3}{python2.7}' ~/.local/bin/colout
$ colout -r colors
COLORS: black, blue, cyan, green, magenta, none, orange, purple, red, white, yellow
```

**Comment by chicks-net** [comment]
This is still an issue on Mint 18.

```
Collecting colout
  Downloading https://files.pythonhosted.org/packages/3d/ba/3ef31c0df3ace69271cc8b1af6b529f24de66ff42c0d99a8d18aa980a307/colout-0.5.tar.gz (47kB)
    100% |████████████████████████████████| 51kB 4.3MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-13kZFS/colout/setup.py", line 25, in <module>
        long_description=open('README.md').read(),
    IOError: [Errno 2] No such file or directory: 'README.md'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-13kZFS/colout/
```

**Comment by nojhan** [comment]
I have no idea how to manage the pip distribution, would anybody want to explain or (better) handle it?
