### ISSUE TITLE
Bug in the "colormap" option

### ISSUE THREAD

**Issue by nojhan** [nojhan/colout#92]
On the develop branch, after 87cac38a482b76cc181db7c9d52729bf87b48fbd.

`echo "pim pam poum" |./colout/colout.py -c p red,green,blue`

```
Traceback (most recent call last):
  File "./colout/colout.py", line 1022, in <module>
  File "./colout/colout.py", line 862, in write_all
  File "./colout/colout.py", line 737, in map_write
  File "./colout/colout.py", line 644, in colorup
  File "./colout/colout.py", line 601, in colorout
  File "./colout/colout.py", line 521, in colorin
  File "./colout/colout.py", line 326, in mode
UnknownColor: colormap

[colout] ERROR: unknown color: colormap (maybe you forgot to install python3-pygments?)
```

Related to the use of the special "colormap" tag.

**Comment by nojhan** [comment]
Fixed.
